# Generated by Django 4.2.2 on 2023-06-12 22:14

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userevent_address'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_details', jsonfield.fields.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_user_event', to='user.userevent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
