# Generated by Django 3.2.4 on 2023-07-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='flat_fee',
            field=models.FloatField(default=1.0),
        ),
    ]
