# Generated by Django 4.2.2 on 2023-06-12 07:50

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.FloatField(default=0.0)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total_seat', models.IntegerField(default=0)),
                ('booked_seat', models.IntegerField(default=0)),
                ('event_type', models.CharField(blank=True, max_length=256, null=True)),
                ('sponser_by', models.CharField(max_length=256)),
                ('artwork_by', models.CharField(max_length=256)),
                ('organized_by', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('service_fee', models.FloatField(default=0.0)),
                ('payment_fee', models.FloatField(default=2.99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
