# Generated by Django 4.2.2 on 2023-06-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='payment_fee',
        ),
        migrations.RemoveField(
            model_name='event',
            name='service_fee',
        ),
        migrations.AddField(
            model_name='event',
            name='payment_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentconfig'),
            preserve_default=False,
        ),
    ]
