# Generated by Django 4.2.2 on 2023-06-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_payment_fee_remove_event_service_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organized_by',
            field=models.CharField(max_length=128),
        ),
    ]
