# Generated by Django 4.2.2 on 2023-06-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userevent_address'),
        ('event', '0003_alter_event_organized_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organized_by',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
    ]
