# Generated by Django 4.2.2 on 2023-06-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment'),
        ('event', '0004_alter_event_organized_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentconfig'),
        ),
    ]
