# Generated by Django 4.2.2 on 2023-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_payment_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_product_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
