# Generated by Django 4.2.2 on 2023-06-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userevent_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='no_of_seats',
            new_name='no_of_tickets',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
