# Generated by Django 4.2.2 on 2023-06-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_no_of_seats_userevent_no_of_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_code',
        ),
    ]
