# Generated by Django 3.2.4 on 2023-07-09 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='user_event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
