# Generated by Django 3.2.4 on 2023-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userevent_user_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='failure_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userevent',
            name='success_mail',
            field=models.BooleanField(default=False),
        ),
    ]
