# Generated by Django 3.2.4 on 2023-07-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230709_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
