# Generated by Django 4.2.2 on 2023-06-12 23:20

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_userevent_address'),
        ('event', '0005_alter_event_payment_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_content', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('thumbnail', 'Thumbnail')], max_length=10)),
                ('content', models.FileField(upload_to=content.models.content_upload_path)),
                ('extention', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('offline_locator', models.CharField(blank=True, max_length=20, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('uploader', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
