# Generated by Django 4.2.2 on 2023-06-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_eventcontent_created_at_eventcontent_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcontent',
            name='offline_locator',
        ),
    ]
