# Generated by Django 3.2.4 on 2023-07-09 08:01

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_payment_id'),
        ('user', '0009_alter_user_gender'),
        ('content', '0003_remove_eventcontent_offline_locator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcontent',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.FileField(upload_to=content.models.event_ticket_content_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
